Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595100%[Finetuning] Epoch: 1 Avg Loss: 0.3118[Validation] Avg Loss: 0.3255, Avg Dice Score: 0.8883100%[Finetuning] Epoch: 2 Avg Loss: 0.3028[Validation] Avg Loss: 0.3234, Avg Dice Score: 0.8919100%[Finetuning] Epoch: 3 Avg Loss: 0.2987[Validation] Avg Loss: 0.3302, Avg Dice Score: 0.8765100%[Finetuning] Epoch: 4 Avg Loss: 0.2958[Validation] Avg Loss: 0.3229, Avg Dice Score: 0.8917100%[Finetuning] Epoch: 5 Avg Loss: 0.2932[Validation] Avg Loss: 0.3250, Avg Dice Score: 0.8837100%[Finetuning] Epoch: 6 Avg Loss: 0.2921[Validation] Avg Loss: 0.3250, Avg Dice Score: 0.8896100%[Finetuning] Epoch: 7 Avg Loss: 0.2922[Validation] Avg Loss: 0.3291, Avg Dice Score: 0.8789100%[Finetuning] Epoch: 8 Avg Loss: 0.2904[Validation] Avg Loss: 0.3328, Avg Dice Score: 0.8722100%[Finetuning] Epoch: 9 Avg Loss: 0.2868[Validation] Avg Loss: 0.3309, Avg Dice Score: 0.8792 100%||[Finetuning] Epoch: 10 Avg Loss: 0.2859143/143 [00:13<00:00, 10.22it/s]143/143 [00:14<00:00, 10.18it/s]143/143 [00:13<00:00, 10.22it/s]143/143 [00:14<00:00, 10.08it/s]143/143 [00:13<00:00, 10.23it/s]143/143 [00:14<00:00, 10.19it/s]143/143 [00:13<00:00, 10.29it/s]143/143 [00:14<00:00, 10.14it/s]143/143 [00:14<00:00, 10.14it/s]143/143 [00:13<00:00, 10.25it/s]er'[Validation] Avg Loss: 0.3297, Avg Dice Score: 0.8845 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to 'self.log()` but the `self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Train Test Results - Average Loss: 0.6412, Average Dice Score: 0.6986