Test Results100%||Average Loss: 0.5151, Average Dice Score: 0.7595[Finetuning] Epoch: 1 Avg Loss: 0.3148[Validation] Avg Loss: 0.3148, Avg Dice Score: 0.8818 100% ||[Finetuning] Epoch: 2 Avg Loss: 0.3064[Validation] Avg Loss: 0.3286, Avg Dice Score: 0.8619100%[Finetuning] Epoch: 3 Avg Loss: 0.3029[Validation] Avg Loss: 0.3151, Avg Dice Score: 0.8807 100%||[Finetuning] Epoch: 4 Avg Loss: 0.2985[Validation] Avg Loss: 0.3172, Avg Dice Score: 0.8751 100% |[Finetuning] Epoch: 5 Avg Loss: 0.2947[Validation] Avg Loss: 0.3174, Avg Dice Score: 0.8746 100% ||[Finetuning] Epoch: 6 Avg Loss: 0.2934[Validation] Avg Loss: 0.3146, Avg Dice Score: 0.8834100%[Finetuning] Epoch: 7 Avg Loss: 0.2927[Validation] Avg Loss: 0.3181, Avg Dice Score: 0.8758 100%||[Finetuning] Epoch: 8 Avg Loss: 0.2898[Validation] Avg Loss: 0.3207, Avg Dice Score: 0.8710 100% |[Finetuning] Epoch: 9 Avg Loss: 0.2895[Validation] Avg Loss: 0.3166, Avg Dice Score: 0.8787 100%||[Finetuning] Epoch: 10 Avg Loss: 0.2866143/143 [00:14<00:00, 10.17it/s]143/143 [00:13<00:00, 10.32it/s]143/143 [00:14<00:00, 10.18it/s]143/143 [00:13<00:00, 10.33it/s]143/143 [00:13<00:00, 10.32it/s]143/143 [00:14<00:00, 10.13it/s]143/143 [00:13<00:00, 10.22it/s]143/143 [00:13<00:00, 10.27it/s]143/143 [00:13<00:00, 10.24it/s]143/143 [00:14<00:00, 10.16it/s]er'[Validation] Avg Loss: 0.3241, Avg Dice Score: 0.8673 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()' but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Train Test Results - Average Loss: 0.6788, Average Dice Score: 0.6880