Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595100%[Finetuning] Epoch: 1 Avg Loss: 0.3167[Validation] Avg Loss: 0.3019, Avg Dice Score: 0.8965 100%||[Finetuning] Epoch: 2 Avg Loss: 0.3069[Validation] Avg Loss: 0.3051, Avg Dice Score: 0.8864100%[Finetuning] Epoch: 3 Avg Loss: 0.3024[Validation] Avg Loss: 0.2992, Avg Dice Score: 0.8946100%[Finetuning] Epoch: 4 Avg Loss: 0.2983[Validation] Avg Loss: 0.2968, Avg Dice Score: 0.8967100%[Finetuning] Epoch: 5 Avg Loss: 0.2989[Validation] Avg Loss: 0.3055, Avg Dice Score: 0.8825100%[Finetuning] Epoch: 6 Avg Loss: 0.2963[Validation] Avg Loss: 0.3043, Avg Dice Score: 0.8865100%[Finetuning] Epoch: 7 Avg Loss: 0.2955[Validation] Avg Loss: 0.2953, Avg Dice Score: 0.8985100%[Finetuning] Epoch: 8 Avg Loss: 0.2916[Validation] Avg Loss: 0.2967, Avg Dice Score: 0.8961100%[Finetuning] Epoch: 9 Avg Loss: 0.2883[Validation] Avg Loss: 0.2979, Avg Dice Score: 0.8973 100%||143/143 [00:13<00:00, 10.58it/s]143/143 [00:13<00:00, 10.57it/s]143/143 [00:13<00:00, 10.55it/s]143/143 [00:13<00:00, 10.64it/s]143/143 [00:13<00:00, 10.63it/s]143/143 [00:13<00:00, 10.68it/s]143/143 [00:13<00:00, 10.49it/s]143/143 [00:13<00:00, 10.55it/s]143/143 [00:13<00:00, 10.48it/s]143/143 [00:13<00:00, 10.47it/s][Finetuning] Epoch: 10 Avg Loss: 0.2886 [Validation] Avg Loss: 0.2981, Avg Dice Score: 0.8960 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the `self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.6348, Average Dice Score: 0.7155