Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595100%[Finetuning] Epoch: 1 Avg Loss: 0.3177[Validation] Avg Loss: 0.2973, Avg Dice Score: 0.9027 100% ||[Finetuning] Epoch: 2 Avg Loss: 0.3100[Validation] Avg Loss: 0.2966, Avg Dice Score: 0.9021100%[Finetuning] Epoch: 3 Avg Loss: 0.3040[Validation] Avg Loss: 0.2935, Avg Dice Score: 0.9072100%[Finetuning] Epoch: 4 Avg Loss: 0.2996[Validation] Avg Loss: 0.2925, Avg Dice Score: 0.9057100%[Finetuning] Epoch: 5 Avg Loss: 0.2960[Validation] Avg Loss: 0.2940, Avg Dice Score: 0.9028100%[Finetuning] Epoch: 6 Avg Loss: 0.2970[Validation] Avg Loss: 0.2964, Avg Dice Score: 0.9011100%[Finetuning] Epoch: 7 Avg Loss: 0.2932[Validation] Avg Loss: 0.2984, Avg Dice Score: 0.8956100%[Finetuning] Epoch: 8 Avg Loss: 0.2916[Validation] Avg Loss: 0.3024, Avg Dice Score: 0.8895100%[Finetuning] Epoch: 9 Avg Loss: 0.2959[Validation] Avg Loss: 0.2980, Avg Dice Score: 0.8987100%[Finetuning] Epoch: 10 Avg Loss: 0.2948[Validation] Avg Loss: 0.3022, Avg Dice Score: 0.8937143/143 [00:13<00:00, 10.44it/s]143/143 [00:13<00:00, 10.34it/s]143/143 [00:13<00:00, 10.37it/s]143/143 [00:13<00:00, 10.24it/s]143/143 [00:13<00:00, 10.44it/s]143/143 [00:13<00:00, 10.34it/s]143/143 [00:13<00:00, 10.33it/s]143/143 [00:14<00:00, 10.18it/s]143/143 [00:13<00:00, 10.40it/s]143/143 [00:13<00:00, 10.40it/s]/home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the `self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.6980, Average Dice Score: 0.6831