Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595 100%||[Finetuning] Epoch: 1 Avg Loss: 0.3168[Validation] Avg Loss: 0.3126, Avg Dice Score: 0.8901 100% |[Finetuning] Epoch: 2 Avg Loss: 0.3069[Validation] Avg Loss: 0.3080, Avg Dice Score: 0.8907 100% |[Finetuning] Epoch: 3 Avg Loss: 0.3014[Validation] Avg Loss: 0.3056, Avg Dice Score: 0.8943 100%||[Finetuning] Epoch: 4 Avg Loss: 0.2986[Validation] Avg Loss: 0.3055, Avg Dice Score: 0.8925100%[Finetuning] Epoch: 5 Avg Loss: 0.2948[Validation] Avg Loss: 0.3082, Avg Dice Score: 0.8876100%[Finetuning] Epoch: 6 Avg Loss: 0.2932[Validation] Avg Loss: 0.3088, Avg Dice Score: 0.8887 100% |[Finetuning] Epoch: 7 Avg Loss: 0.2920[Validation] Avg Loss: 0.3114, Avg Dice Score: 0.8858 100%||[Finetuning] Epoch: 8 Avg Loss: 0.2923[Validation] Avg Loss: 0.3043, Avg Dice Score: 0.8991100%[Finetuning] Epoch: 9 Avg Loss: 0.2885[Validation] Avg Loss: 0.3053, Avg Dice Score: 0.8971100%[Finetuning] Epoch: 10 Avg Loss: 0.2864143/143 [00:13<00:00, 10.49it/s]143/143 [00:13<00:00, 10.59it/s]143/143 [00:13<00:00, 10.63it/s]143/143 [00:13<00:00, 10.48it/s]143/143 [00:13<00:00, 10.54it/s]143/143 [00:13<00:00, 10.44it/s]143/143 [00:13<00:00, 10.30it/s]143/143 [00:13<00:00, 10.43it/s]143/143 [00:13<00:00, 10.39it/s]143/143 [00:13 00:00, 10.36it/s][Validation] Avg Loss: 0.3041, Avg Dice Score: 0.8950 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to 'self.log()` but the `self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.6435, Average Dice Score: 0.7030