Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595100%[Finetuning] Epoch: 1 Avg Loss: 0.3164[Validation] Avg Loss: 0.3040, Avg Dice Score: 0.9014100%[Finetuning] Epoch: 2 Avg Loss: 0.3055[Validation] Avg Loss: 0.3027, Avg Dice Score: 0.9040 100%||[Finetuning] Epoch: 3 Avg Loss: 0.3015[Validation] Avg Loss: 0.3033, Avg Dice Score: 0.9081 100% |[Finetuning] Epoch: 4 Avg Loss: 0.2984[Validation] Avg Loss: 0.3005, Avg Dice Score: 0.9032 100% ||[Finetuning] Epoch: 5 Avg Loss: 0.2953[Validation] Avg Loss: 0.2989, Avg Dice Score: 0.9048100%[Finetuning] Epoch: 6 Avg Loss: 0.2928[Validation] Avg Loss: 0.3104, Avg Dice Score: 0.8880 100%||[Finetuning] Epoch: 7 Avg Loss: 0.2912[Validation] Avg Loss: 0.3096, Avg Dice Score: 0.9022 100% |[Finetuning] Epoch: 8 Avg Loss: 0.2903[Validation] Avg Loss: 0.3034, Avg Dice Score: 0.8986 100%||[Finetuning] Epoch: 9 Avg Loss: 0.2888[Validation] Avg Loss: 0.3057, Avg Dice Score: 0.8937100%[Finetuning] Epoch: 10 Avg Loss: 0.2900143/143 [00:13<00:00, 10.60it/s]143/143 [00:13<00:00, 10.65it/s]143/143 [00:13<00:00, 10.48it/s]143/143 [00:13<00:00, 10.53it/s]143/143 [00:13<00:00, 10.65it/s]143/143 [00:13<00:00, 10.55it/s]143/143 [00:13<00:00, 10.48it/s]143/143 [00:13<00:00, 10.56it/s]143/143 [00:13<00:00, 10.62it/s]143/143 [00:13 00:00, 10.70it/s][Validation] Avg Loss: 0.3053, Avg Dice Score: 0.8959 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'TrainerTest Results - Average Loss: 0.6014, Average Dice Score: 0.7188