Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595100%[Finetuning] Epoch: 1 Avg Loss: 0.3162[Validation] Avg Loss: 0.3041, Avg Dice Score: 0.8961100%[Finetuning] Epoch: 2 Avg Loss: 0.3064[Validation] Avg Loss: 0.3043, Avg Dice Score: 0.8945 100%||[Finetuning] Epoch: 3 Avg Loss: 0.3021[Validation] Avg Loss: 0.2997, Avg Dice Score: 0.9004 100% |[Finetuning] Epoch: 4 Avg Loss: 0.2991[Validation] Avg Loss: 0.3026, Avg Dice Score: 0.8943 100% ||[Finetuning] Epoch: 5 Avg Loss: 0.2990[Validation] Avg Loss: 0.3014, Avg Dice Score: 0.8966100%[Finetuning] Epoch: 6 Avg Loss: 0.2936[Validation] Avg Loss: 0.3126, Avg Dice Score: 0.8773 100%||[Finetuning] Epoch: 7 Avg Loss: 0.2920[Validation] Avg Loss: 0.3041, Avg Dice Score: 0.8922 100% |[Finetuning] Epoch: 8 Avg Loss: 0.2914[Validation] Avg Loss: 0.3047, Avg Dice Score: 0.8898 100%||[Finetuning] Epoch: 9 Avg Loss: 0.2892[Validation] Avg Loss: 0.3026, Avg Dice Score: 0.8931100%[Finetuning] Epoch: 10 Avg Loss: 0.2874143/143 [00:13<00:00, 10.57it/s]143/143 [00:13<00:00, 10.56it/s]143/143 [00:13<00:00, 10.57it/s]143/143 [00:13<00:00, 10.53it/s]143/143 [00:13<00:00, 10.62it/s]143/143 [00:13<00:00, 10.45it/s]143/143 [00:13<00:00, 10.58it/s]143/143 [00:13<00:00, 10.57it/s]143/143 [00:13<00:00, 10.60it/s]143/143 [00:13 00:00, 10.56it/s][Validation] Avg Loss: 0.3152, Avg Dice Score: 0.8775 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'TrainerTest Results - Average Loss: 0.6724, Average Dice Score: 0.6812