Test Results - Average Loss: 0.5151, Average Dice Score: 0.7595 100% ||[Finetuning] Epoch: 1 Avg Loss: 0.3130[Validation] Avg Loss: 0.3315, Avg Dice Score: 0.8927100%[Finetuning] Epoch: 2 Avg Loss: 0.3032[Validation] Avg Loss: 0.3302, Avg Dice Score: 0.8929 100% ||[Finetuning] Epoch: 3 Avg Loss: 0.2997[Validation] Avg Loss: 0.3301, Avg Dice Score: 0.8942100%[Finetuning] Epoch: 4 Avg Loss: 0.2967[Validation] Avg Loss: 0.3305, Avg Dice Score: 0.8900 100%||[Finetuning] Epoch: 5 Avg Loss: 0.2942[Validation] Avg Loss: 0.3298, Avg Dice Score: 0.8927 100% |[Finetuning] Epoch: 6 Avg Loss: 0.2921[Validation] Avg Loss: 0.3270, Avg Dice Score: 0.8937 100% ||[Finetuning] Epoch: 7 Avg Loss: 0.2883[Validation] Avg Loss: 0.3274, Avg Dice Score: 0.8913100%[Finetuning] Epoch: 8 Avg Loss: 0.2873[Validation] Avg Loss: 0.3285, Avg Dice Score: 0.8949 100%||[Finetuning] Epoch: 9 Avg Loss: 0.2867[Validation] Avg Loss: 0.3280, Avg Dice Score: 0.8924 100%||[Finetuning] Epoch: 10 Avg Loss: 0.2848143/143 [00:13<00:00, 10.47it/s]143/143 [00:13<00:00, 10.57it/s]143/143 [00:13<00:00, 10.71it/s]143/143 [00:13<00:00, 10.58it/s]143/143 [00:13<00:00, 10.62it/s]143/143 [00:13<00:00, 10.68it/s]143/143 [00:13<00:00, 10.49it/s]143/143 [00:13<00:00, 10.55it/s]143/143 [00:13<00:00, 10.43it/s]143/143 [00:13 00:00, 10.57it/s][Validation] Avg Loss: 0.3290, Avg Dice Score: 0.8938 /home/mikhelson/MedImSeg-Lab24/CLUE/lib/python3.8/site-packages/lightning/pytorch/core/module.py:447: You are trying to `self.log()` but the 'self.trainer reference is not registered on the model yet. This is most likely because the model hasn't been passed to the 'Trainer'Test Results - Average Loss: 0.5757, Average Dice Score: 0.7480